# escape=`
FROM microsoft/windowsservercore as msi

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN     Invoke-WebRequest 'https://go.microsoft.com/fwlink/?LinkId=746572' -OutFile 'v15_vc_redist.x64.exe' -UseBasicParsing ;  `
        Start-Process c:\v15_vc_redist.x64.exe -ArgumentList '/install /passive /norestart' -Wait ; `
        Invoke-WebRequest 'https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe' -OutFile 'v10_vc_redist.x64.exe' -UseBasicParsing ; `
        Start-Process c:\v10_vc_redist.x64.exe -ArgumentList '/install /passive /norestart' -Wait 

RUN Invoke-WebRequest 'https://ci.appveyor.com/api/buildjobs/80dp14k90koyq1d9/artifacts/php-7.2.0RC2-vc15-x64.zip' -OutFile 'php72.zip' -UseBasicParsing ; `
    mkdir c:\pocketmine ; `
    Expand-Archive php72.zip -DestinationPath C:\pocketmine; 

RUN Invoke-WebRequest 'https://github.com/pmmp/PocketMine-MP/releases/download/api%2F3.0.0-ALPHA8/PocketMine-MP_1.7dev-83_6e5759b1_API-3.0.0-ALPHA8.phar' -OutFile 'pocketmine-MP.phar' -UseBasicParsing ; `
    move pocketmine-MP.phar  C:\pocketmine\pocketmine-MP.phar ; 

RUN del c:\v*_vc_redist.x64 -force ; `
    del php72.zip ;

# FROM microsoft/nanoserver
# SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
# COPY --from=msi C:\windows\system32\imm32.dll C:\windows\system32
# COPY --from=msi C:\windows\system32\msvcr100.dll C:\windows\system32
# COPY --from=msi C:\windows\system32\msvcp140.dll C:\windows\system32
# COPY --from=msi C:\windows\system32\vcruntime140.dll C:\windows\system32
# COPY --from=msi C:\pocketmine C:\pocketmine

EXPOSE 19132

EXPOSE 80

VOLUME c:\data

RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices' -Name 'G:' -Value "\??\C:\data" -Type String;  

COPY assets pocketmine

WORKDIR c:\pocketmine

CMD ["run.cmd"]