# escape=`
FROM microsoft/windowsservercore as msi

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN  Invoke-WebRequest 'https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe' -OutFile 'v14_vc_redist.x64.exe' -UseBasicParsing ; `
      Start-Process c:\v14_vc_redist.x64.exe -ArgumentList '/install /passive /norestart' -Wait

RUN Invoke-WebRequest 'http://windows.php.net/downloads/qa/php-7.2.0RC2-Win32-VC15-x64.zip' -OutFile 'php72.zip' -UseBasicParsing ; `
    mkdir c:\php72 ; `
    Expand-Archive php72.zip -DestinationPath C:\php72 ; 

RUN Invoke-WebRequest 'https://github.com/pmmp/PocketMine-MP/releases/download/api%2F3.0.0-ALPHA8/PocketMine-MP_1.7dev-83_6e5759b1_API-3.0.0-ALPHA8.phar' -OutFile 'pocketmine.phar' -UseBasicParsing ; `
    mkdir c:\pocketmine ; `
    move pocketmine.phar  C:\pocketmine\poketmine.phar ; 


FROM microsoft/nanoserver

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

 COPY --from=msi C:\windows\system32\msvcp140.dll C:\windows\system32
 COPY --from=msi C:\windows\system32\vcruntime140.dll C:\windows\system32
 COPY --from=msi C:\php72 C:\php

 RUN $env:PATH = 'C:\php;{0}' -f $env:PATH ; `
    Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\' -Name Path -Value $env:PATH ; 
  
EXPOSE 19132
EXPOSE 80

COPY --from=msi C:\pocketmine C:\pocketmine

VOLUME c:/data

CMD [ "powershell.exe" ]