# escape=`
FROM microsoft/windowsservercore as msi

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Invoke-WebRequest 'https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe' -OutFile 'v14_vc_redist.x64.exe' -UseBasicParsing ; `
    Start-Process c:\v14_vc_redist.x64.exe -ArgumentList '/install /passive /norestart' -Wait

RUN Invoke-WebRequest 'http://windows.php.net/downloads/qa/php-7.2.0RC3-nts-Win32-VC15-x64.zip' -OutFile 'php.zip' -UseBasicParsing ; `
    mkdir c:\php ; `
    Expand-Archive php.zip -DestinationPath C:\php; 

RUN Invoke-WebRequest 'https://ci.appveyor.com/api/buildjobs/80dp14k90koyq1d9/artifacts/php-7.2.0RC2-vc15-x64.zip' -OutFile 'php72.zip' -UseBasicParsing ; `
    mkdir c:\pocketmine ; `
    Expand-Archive php72.zip -DestinationPath C:\pocketmine; 
    
COPY assets assets

VOLUME c:\data

CMD [ "powershell.exe" ]
