# escape=`
FROM microsoft/windowsservercore as msi

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Invoke-WebRequest 'https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe' -OutFile 'v14_vc_redist.x64.exe' -UseBasicParsing ; `
    Start-Process c:\v14_vc_redist.x64.exe -ArgumentList '/install /passive /norestart' -Wait

RUN Invoke-WebRequest 'https://github.com/BlueLightJapan/BinaryPackforWindows/archive/master.zip' -OutFile 'binpack.zip' -UseBasicParsing ; `
    Expand-Archive binpack.zip -DestinationPath C:\ ; `
    del .\BinaryPackforWindows-master\bin\ -Force -Recurse ; `
    mv .\BinaryPackforWindows-master\64bit\bin\ .\BinaryPackforWindows-master\bin ; `
    del .\BinaryPackforWindows-master\64bit\ ; `
    del .\BinaryPackforWindows-master\*.exe ; `
    mv .\BinaryPackforWindows-master\ .\bluelight ;

RUN Invoke-WebRequest 'http://jenkins.haniokasai.com/job/BlueLight-PMMP/ws/artifacts/BlueLight-PHP7.phar' -OutFile 'c:\bluelight\bluelight-php7.phar' -UseBasicParsing ; 

COPY assets bluelight

#FROM microsoft/nanoserver
#SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
#COPY --from=msi C:\windows\system32\msvcp140.dll C:\windows\system32
#COPY --from=msi C:\windows\system32\vcruntime140.dll C:\windows\system32
#COPY --from=msi C:\bluelight C:\bluelight

EXPOSE 19132
EXPOSE 80

VOLUME c:\data

RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices' -Name 'G:' -Value "\??\C:\data" -Type String;  

WORKDIR c:\bluelight 

CMD ["run.cmd"]