# escape=`
FROM microsoft/windowsservercore as msi

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Invoke-WebRequest 'https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe' -OutFile 'v14_vc_redist.x64.exe' -UseBasicParsing ; `
    Start-Process c:\v14_vc_redist.x64.exe -ArgumentList '/install /passive /norestart' -Wait

RUN Invoke-WebRequest 'http://windows.php.net/downloads/releases/php-7.0.23-Win32-VC14-x64.zip' -OutFile 'php70.zip' -UseBasicParsing ; `
    mkdir c:\php70 ; `
    Expand-Archive php70.zip -DestinationPath C:\php70 ; 

RUN mkdir c:\bluelight ; `
    Invoke-WebRequest 'http://jenkins.haniokasai.com/job/BlueLight-PMMP/ws/artifacts/BlueLight-PHP7.phar' -OutFile 'c:\bluelight\bluelight.phar' -UseBasicParsing ; 


FROM microsoft/nanoserver

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

COPY --from=msi C:\windows\system32\msvcp140.dll C:\windows\system32
COPY --from=msi C:\windows\system32\vcruntime140.dll C:\windows\system32
COPY --from=msi C:\php70 C:\php

RUN $env:PATH = 'C:\php;{0}' -f $env:PATH ; `
    Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\' -Name Path -Value $env:PATH ; 
  
EXPOSE 19132
EXPOSE 80

COPY --from=msi C:\bluelight C:\bluelight

VOLUME c:/data

CMD [ "powershell.exe" ]